import { NextResponse } from 'next/server';
import { getServerSession } from 'next-auth';
import { authOptions } from '@/lib/auth';
import prisma from '@/lib/prisma';
import { isActiveCarePlanStatus } from '@/lib/care-plan-status';
import { logAuditEvent } from '@/lib/audit-log';
import { rateLimit } from '@/lib/rate-limit';

// Frequencies that should NOT be auto-generated (require manual creation)
const NON_AUTO_GENERATED_FREQUENCIES = ['AS_NEEDED', 'CUSTOM'];

// Frequencies that support auto-generation
const AUTO_GENERATED_FREQUENCIES = ['DAILY', 'WEEKLY', 'BI_WEEKLY', 'MONTHLY'];

export async function POST(request, { params }) {
  try {
    const session = await getServerSession(authOptions);

    if (!session || !session.user) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    const { id } = params;
    const body = await request.json();

    const { startDate, endDate, staffId } = body;

    const rateLimitResult = await rateLimit(`care-plans:generate:${session.user.id}`, {
      maxRequests: 10,
      windowMs: 60 * 1000,
    });
    if (!rateLimitResult.success) {
      return NextResponse.json(
        { error: 'Too many generation requests. Please try again shortly.' },
        {
          status: 429,
          headers: { 'Retry-After': String(Math.ceil(rateLimitResult.retryAfterMs / 1000)) },
        }
      );
    }

    if (!startDate || !endDate) {
      return NextResponse.json(
        { error: 'Start date and end date are required' },
        { status: 400 }
      );
    }

    const carePlan = await prisma.carePlan.findFirst({
      where: {
        id,
        organizationId: session.user.organizationId,
      },
      include: {
        services: {
          include: {
            service: true,
          },
        },
        client: true,
      },
    });

    if (!carePlan) {
      return NextResponse.json({ error: 'Care plan not found' }, { status: 404 });
    }

    if (!isActiveCarePlanStatus(carePlan.status)) {
      return NextResponse.json(
        { error: 'Only active care plans can generate visits' },
        { status: 400 }
      );
    }

    const resolvedBranchId = carePlan.branchId || carePlan.client?.branchId || null;
    if (!resolvedBranchId) {
      return NextResponse.json(
        { error: 'Unable to resolve a branch for this care plan' },
        { status: 400 }
      );
    }

    const start = new Date(startDate);
    const end = new Date(endDate);

    if (Number.isNaN(start.getTime()) || Number.isNaN(end.getTime()) || end < start) {
      return NextResponse.json(
        { error: 'End date must be the same as or after the start date' },
        { status: 400 }
      );
    }

    const createdVisits = [];
    const skippedDuplicates = [];
    const skippedConflicts = [];
    const skippedNonAutoGenerated = [];

    // Generate visits for each service
    for (const planService of carePlan.services) {
      const service = planService.service;
      const frequency = planService.frequency;

      // Skip AS_NEEDED and CUSTOM frequencies - they require manual visit creation
      if (NON_AUTO_GENERATED_FREQUENCIES.includes(frequency)) {
        skippedNonAutoGenerated.push({
          serviceId: service.id,
          serviceName: service.name,
          frequency,
          reason: `${frequency} visits require manual creation`,
        });
        continue; // Skip this service and continue with the rest
      }

      // Only process auto-generated frequencies
      if (!AUTO_GENERATED_FREQUENCIES.includes(frequency)) {
        continue;
      }

      let currentDate = new Date(start);

      while (currentDate <= end) {
        const duration = service.duration || 60;
        const visitStart = new Date(currentDate);
        visitStart.setHours(9, 0, 0, 0); // Default 9 AM - explicit default since no time config in schema
        const visitEnd = new Date(visitStart);
        visitEnd.setMinutes(visitEnd.getMinutes() + duration);

        const visitData = {
          title: `${service.name} - ${currentDate.toLocaleDateString()}`,
          description: `Scheduled visit from care plan: ${carePlan.name}`,
          startTime: visitStart.toISOString(),
          endTime: visitEnd.toISOString(),
          status: 'SCHEDULED',
          organizationId: carePlan.organizationId,
          branchId: resolvedBranchId,
          carePlanId: carePlan.id,
          serviceId: service.id,
          clientId: carePlan.clientId,
          staffId: staffId || carePlan.staffId || null,
        };

        // Check for duplicate visit (same organization, care plan, client, service, time)
        const existingVisit = await prisma.visit.findFirst({
          where: {
            organizationId: carePlan.organizationId,
            carePlanId: carePlan.id,
            clientId: carePlan.clientId,
            serviceId: service.id,
            startTime: visitStart,
            endTime: visitEnd,
          },
        });

        if (existingVisit) {
          skippedDuplicates.push({
            date: visitStart.toISOString(),
            serviceId: service.id,
            serviceName: service.name,
            reason: 'Duplicate visit already exists',
          });
        } else {
          // Check for conflicts using strict overlap logic (allows back-to-back visits)
          let hasConflict = false;
          let conflictType = null;

          // Check staff conflict if staff is assigned
          if (visitData.staffId) {
            const staffConflicts = await prisma.visit.findMany({
              where: {
                staffId: visitData.staffId,
                organizationId: carePlan.organizationId,
                status: { not: 'CANCELLED' },
                OR: [
                  {
                    startTime: { lt: visitEnd },
                    endTime: { gt: visitStart },
                  },
                ],
              },
              select: { id: true, startTime: true, endTime: true },
            });

            if (staffConflicts.length > 0) {
              hasConflict = true;
              conflictType = 'STAFF';
            }
          }

          // Check client conflict
          if (!hasConflict) {
            const clientConflicts = await prisma.visit.findMany({
              where: {
                clientId: carePlan.clientId,
                organizationId: carePlan.organizationId,
                status: { not: 'CANCELLED' },
                OR: [
                  {
                    startTime: { lt: visitEnd },
                    endTime: { gt: visitStart },
                  },
                ],
              },
              select: { id: true, startTime: true, endTime: true },
            });

            if (clientConflicts.length > 0) {
              hasConflict = true;
              conflictType = 'CLIENT';
            }
          }

          if (hasConflict) {
            skippedConflicts.push({
              date: visitStart.toISOString(),
              serviceId: service.id,
              serviceName: service.name,
              conflictType,
              reason: `${conflictType} conflict detected at this time`,
            });
          } else {
            // Create the visit
            const visit = await prisma.visit.create({
              data: visitData,
            });
            createdVisits.push(visit);
          }
        }

        // Move to next date based on frequency
        switch (frequency) {
          case 'DAILY':
            currentDate.setDate(currentDate.getDate() + 1);
            break;
          case 'WEEKLY':
            currentDate.setDate(currentDate.getDate() + 7);
            break;
          case 'BI_WEEKLY':
            currentDate.setDate(currentDate.getDate() + 14);
            break;
          case 'MONTHLY':
            currentDate.setMonth(currentDate.getMonth() + 1);
            break;
          default:
            currentDate.setDate(currentDate.getDate() + 1);
        }
      }
    }

    const responseBody = {
      success: true,
      visitsCreated: createdVisits.length,
      visits: createdVisits,
      skippedDuplicates,
      skippedConflicts,
      skippedNonAutoGenerated,
    };

    await logAuditEvent({
      action: 'GENERATE_VISITS',
      entity: 'CarePlan',
      entityId: carePlan.id,
      userId: session.user.id,
      after: {
        carePlanId: carePlan.id,
        visitsCreated: createdVisits.length,
        skippedDuplicates: skippedDuplicates.length,
        skippedConflicts: skippedConflicts.length,
        skippedNonAutoGenerated: skippedNonAutoGenerated.length,
        staffId: staffId || null,
        startDate,
        endDate,
      },
    });

    return NextResponse.json(responseBody);
  } catch (error) {
    console.error('Error generating visits:', error);
    return NextResponse.json({ error: 'Failed to generate visits' }, { status: 500 });
  }
}
